const Connection = 
    {
        url: "http://app.p2b-ethiopia.com/",
        signUp: "Signup.php",
        signIn: "Signin.php",
        googleSignUp: "GoogleSignUp.php",
        googleSignIn: "GoogleSignIn.php",
        AddEvent: "AddEvent.php",
        TodayEvents: "TodayEvents.php",
        follow: "follow.php",
        upload: "uploadimage.php",
        assets: "assets/",
        organizer: "organizer.php",
        search: "search.php",
        notification: "notification.php",
        profile: "UserProfile.php",
        updateProfile: "updateProfile.php",
        userInfo: "userInfo.php",
        MetaData: "MetaData.php",
        updateUserInfo: "updateUserInfo.php",
        ChangePassword: "changePassword.php",
        WeekEvents: "WeekEvents.php",
        UpcomingEvents: "UpcomingEvents.php",
        categoryFilter: "categoryFilter.php",
        YourEvents: "YourEvents.php",
        OrganizerFollowCounter: "organizerFollowers.php",
        organizerEvents: "OrganizerEvents.php",
        FeedBacks: "FeedBacks.php",
        forgotPassword: "forgotPassword.php",
        status: "status.php",
    }

export default Connection;